# ---- neotree ----
[[plugins]]
repo = "nvim-neo-tree/neo-tree.nvim"
depends = [
  "plenary.nvim",
  "nui.nvim",
  "nvim-web-devicons",
]
on_cmd = ["Neotree"]
lua_source = '''
  require("config/neotree")
'''

[[plugins]]
repo = "nvim-lua/plenary.nvim"

[[plugins]]
repo = "MunifTanjim/nui.nvim"

[[plugins]]
repo = "nvim-tree/nvim-web-devicons"

# --- fzf
[[plugins]]
repo = "nvim-telescope/telescope.nvim"
depends = [
  "plenary.nvim",
]

# --- code companion
[[plugins]]
repo = "olimorris/codecompanion.nvim"
depends = [
  "plenary.nvim",
]

# --- markdown
[[plugins]]
repo = "MeanderingProgrammer/render-markdown.nvim"
