[[plugins]]
repo = "neovim/nvim-lspconfig"
depends = [
  "lazydev.nvim",
  "nvim-treesitter",
  "nvim-cmp",
  "cmp-nvim-lsp",
  "lspkind.nvim",
]

# ---- others ----
[[plugins]]
repo = "folke/lazydev.nvim"

# --- treesitter
[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter-textobjects"
depends = [
   "nvim-treesitter"
]

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter-context"
depends = [
   "nvim-treesitter"
]

# --- cmp
[[plugins]]
repo = "hrsh7th/nvim-cmp"

[[plugins]]
repo = "hrsh7th/cmp-nvim-lsp"

[[plugins]]
repo = "onsails/lspkind.nvim"
